Button loading state
AirLabsTeam/air-core pull request #69
Opened 2020-12-14 16:16 UTC by lin-jessica

2020-12-14 23:45 UTC, kylemh reviewed
Last bit:

Can you use: `const shouldReduceMotion = useReducedMotion();` to prevent animations when a user is hoping to avoid them?

https://www.framer.com/api/motion/guide-accessibility/

Everything else is perfect IMO.

2020-12-15 01:06 UTC, andyhqtran requested changes

2020-12-15 01:06 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +const sizeMap: { [key in ButtonSize]: 4 | 5 } = {
Can we just keep it all at `4`? It's very pixelated at 5

2020-12-15 01:06 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +  0% {transform: translate(0,0)}
There needs do have a negative `y` value otherwise the animation isn't centered

2020-12-15 01:06 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +  50% {transform: translate(0,3px)}
> https://github.com/AirLabsTeam/next/pull/432
Add-on: Can we make this 4?

2020-12-15 14:01 UTC, lin-jessica commented on packages/zephyr/src/Button.tsx
> +  50% {transform: translate(0,3px)}
Had it at 4 but design asked to shorten the motion and were happy with what they saw at 3px

2020-12-15 14:17 UTC, lin-jessica commented on packages/zephyr/src/Button.tsx
> +const sizeMap: { [key in ButtonSize]: 4 | 5 } = {
I'll confirm with mari!

2020-12-15 17:33 UTC, lin-jessica commented on packages/zephyr/src/Button.tsx
> +      'Button can only have loading state if it is a filled variant',
design confirmed loading animation is only for filled buttons, they will update figma. was there discussion otherwise?

2020-12-15 17:38 UTC, kylemh commented on packages/zephyr/src/theme/variants/button.ts
> +    '&:not(.isLoading):active': {
@andyhqtran you mean `&:hover:not(.isLoading)`?

2020-12-15 17:47 UTC, lin-jessica commented on packages/zephyr/src/Button.tsx
> +            isLoading ? (
Decided to let the button change size in order to fit `Loading...` text

2020-12-15 18:33 UTC, kylemh commented on packages/zephyr/src/Button.tsx
> +            isLoading ? (
What do you mean by this?

2020-12-15 18:51 UTC, kylemh commented on packages/zephyr/src/Button.tsx
> +              <Loader isLoading={isLoading}>
```suggestion
              <VisuallyHidden>Loading...</VisuallyHidden>
              <Loader isLoading={isLoading} aria-hidden="true">
```

2020-12-15 21:41 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +  50% {transform: translate(0,3px)}
This will make it a little tricky to keep the animation centered causing you to have to go into sub-pixel territory which can be flakey

2020-12-15 21:42 UTC, andyhqtran commented on packages/zephyr/src/theme/variants/button.ts
> +    '&:not(.isLoading):active': {
My bad, yeah it should come after `&:hover`

2020-12-15 21:46 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +  0% {transform: translate(0,0)}
Can we add the spacing in between the `{` and the value?

2020-12-15 21:47 UTC, andyhqtran commented on packages/zephyr/src/Button.tsx
> +      'Button can only have loading state if it is a filled variant',
There wasn't additional discussion, just wanted to see if it was something that was brought up

2020-12-16 02:44 UTC, closed without merging